Parameters:
  BucketName:
    Type: String
Resources:
  PocketLogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
  PocketLogLogsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref PocketLogRole
      PolicyName: pocketlog-cloudwatch
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - logs:*
            Resource:
              - arn:aws:logs:*:*:*
  PocketLogS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref PocketLogRole
      PolicyName: !Sub
        - ${Domain}-writer
        - Domain: !Ref BucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !Sub
              - arn:aws:s3:::${bucket}
              - bucket: !Ref BucketName
          -
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
            Resource: !Sub
              - arn:aws:s3:::${bucket}/*
              - bucket: !Ref BucketName
